name: Dependabot auto-merge
true: pull_request
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - id: metadata
      name: Dependabot metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
      name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --merge "$PR_URL"
